version: '3.1'

services:
    lagerlandfrontend:
        container_name: LagerLandFrontend
        build: ./frontend
        ports:
            - 80:80

    lagerlandbackend:
        container_name: LagerLandBackend
        build: ./backend
        environment:
            DB_HOST: mariadb_lager
            DB_USER: lagerland
            DB_PASSWORD: 91gSn2CF83cySuuS5doQ
            TOKEN_KEY: lagerland # Token key for JWT

    mariadb_lager:
        container_name: mariadb_lager
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - mariadb_lager_db=/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: t5gE4zmRsUF9S9YTG11U
            MARIADB_DATABASE: lagerland
            MARIADB_USER: lagerland
            MARIADB_PASSWORD: 91gSn2CF83cySuuS5doQ

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8080:8080
        environment:
            - ADMINER_DESIGN=pappu687

volumes:
    mariadb_lager_db:
